# Generated by Django 4.2.10 on 2024-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.TextField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
