# Generated by Django 4.2.10 on 2024-02-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_specialization'),
        ('patient', '0002_patient_otp_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('time', models.TimeField(max_length=50, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('status', models.TextField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
